### ISSUE TITLE
Awesome initiative!

### ISSUE THREAD

**Issue by tokejepsen** [jasperges/pyblish-blender#1]
Great to see this :)

Is this a working version?

Maybe you would be interested in moving it to an official repository at https://github.com/pyblish ?

**Comment by jasperges** [comment]
Hi Toke,

It does work, but there are several gotchas. I will try to check everything again (also with the latest pyblish/pyblish QML versions) and make a list of things I encounter. Then we could have a look if it's worth it to move to the official Pyblish repo and also see if we can 'fix' some things.

**Comment by hannesdelbeke** [comment]
hello, 
is there still interests in merging this to https://github.com/pyblish/pyblish-blender ?
might need an update for the menu button, but overall still seems to work in latest blender

made a PR to merge into the official repo https://github.com/pyblish/pyblish-blender/pull/2
which maintains all history of your repo
edit: just been told I might be doing a hostile fork, apologies 🙈
