### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by asztalosdani** [jasperges/pyblish-blender#2]
Hi,

I have downloaded pyblish, pyblish_qml and pyblish_blender. I have a separate python 3 install with PyQt5, and I set the PYBLISH_QML_PYTHON_EXECUTABLE.
I can import pyblish and pyblish_qml, but when running `import pyblish_blender` it fails with `ImportError: cannot import name 'QtWidgets'`. After further inspection it turns out I cannot import PyQt5 from blender, because it gives `ImportError: DLL load failed: The specified module could not be found.`
So the question is, how to set it up properly?

**Comment by jasperges** [comment]
You also have to install PyQt5 under Blender. You can easily install it from the commandline with pip:

```bash
$ <blender_python_exec> -m ensurepip
$ <blender_pip> install pyqt5
```
`<blender_python_exec>` is the Python executable from Blender. `<blender_pip>` is the version of pip that just got installed, it should be next to `<blender_python_exec>`.

Alternatively you can run this script from within Blender:

```python
import subprocess

import bpy


def main():
    completedprocess = subprocess.run(
        [bpy.app.binary_path_python, '-m', 'ensurepip'],
        stderr=subprocess.PIPE,
    )
    if completedprocess.returncode != 0:
        raise Exception(completedprocess.stderr.decode())
    import pip
    pip.main(['install', 'pyqt5'])


if __name__ == "__main__":
    main()
```

Another thing to note is that it is not completely stable. I think this has to do with how threads are running, which has [know limitations in Blender](https://docs.blender.org/api/blender_python_api_current/info_gotcha.html#strange-errors-using-threading-module).
And also related to this is that `bpy.context` is mostly empty when accessed from within a pyblish plugin.
At some point I hope I have some time to look into these issues and see how they can be fixed.
But still, it works fairly well. Just be sure to save your blend file before running pyblish.

**Comment by OlafHaag** [comment]
Hi! I know it's been quite a while since anything happened with pyblish-blender. Could you please try to help me out, regardless? I turned it into a proper add-on that can install the dependencies, and I can show the pyblish-lite GUI, for example, but ~it's blocking Blender, so~ I'd prefer pyblish-qml. But I can't  get it to import the PyQt5 or PySide2 modules on `show()`. I always get and error that the specified module was not found.

```
Pyblish: Registered C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\pyblish_blender\plugins
Setting up Pyblish QML in Blender
uninstalling..
Installing..
Using Python @ 'C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.EXE'
Using PyQt5 @ 'C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages'
Targets: default
PySide2/__init__.py: Unable to import shiboken2 from C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pyblish_qml\ipc, C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages, C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python39.zip, C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\DLLs, C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib, C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin, C:\Program Files\Blender Foundation\Blender 2.93\2.93\python
Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pyblish_qml\vendor\Qt5.py", line 18, in <module>
from PySide2 import (
File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\PySide2\__init__.py", line 107, in <module>
_setupQtDirectories()
File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\PySide2\__init__.py", line 58, in _setupQtDirectories
import shiboken2
File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\shiboken2\__init__.py", line 27, in <module>
from .shiboken2 import *
ImportError: DLL load failed while importing shiboken2: Das angegebene Modul wurde nicht gefunden.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pyblish_qml\__main__.py", line 6, in <module>
from . import app
File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pyblish_qml\app.py", line 12, in <module>
from . import util, compat, control, settings, ipc
File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pyblish_qml\util.py", line 10, in <module>
from .vendor.Qt5 import QtCore
File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pyblish_qml\vendor\Qt5.py", line 42, in <module>
from PyQt5 import (
ModuleNotFoundError: No module named 'PyQt5'
```
I also tried pointing to a site-packages folder of a conda environment with PySide2, pyblish-qml, and pyblish-base installed, but calling show() then just makes blender unresponsive, nothing else happens.

In the conda environment I can run `python -m pyblish_qml --demo` successfully, but trying to call this with Blender's python also throws above error.

After registering plugins and host I do:
```Python
def register_gui():
    pyblish_qml.api.register_python_executable(sys.executable)
    pyblish_qml.api.register_pyqt5(site.getsitepackages()[-1])
    pyblish.api.register_gui("pyblish_lite")
    pyblish.api.register_gui("pyblish_qml")
```
Any idea what could cause the issue and how to make it work? In the meantime, I'll try to get permission from the company to make the repo public.

**Comment by OlafHaag** [comment]
I also did the obvious thing and followed **your** installation instruction with your pyblish_blender version. Interestingly enough, `pyblish_lite.show()` works, but `pyblish_qml.show()` throws `ImportError: DLL load failed: Permission denied` error, which I also get with my add-on in certain conditions.
I'm on Windows 10.

**Comment by OlafHaag** [comment]
Following a suggestion from stackoverflow, I manually copied the *python3.dll* from the base installation folder to the *2.93/python/bin/* folder, where previously only **python.exe**, and **python39.dll** resided.
Despite manually copying a DLL around being less than ideal, mildly speaking, it seemed to have solved the import issue, just to present a new challenge:

```
Pyblish: Registered C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\pyblish_blender\plugins
Setting up Pyblish QML in Blender
uninstalling..
Installing..
Using Python @ 'C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.EXE'
Using PyQt5 @ 'C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages'
Targets: default
Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pyblish_qml\__main__.py", line 6, in <module>
from . import app
File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pyblish_qml\app.py", line 12, in <module>
from . import util, compat, control, settings, ipc
File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pyblish_qml\control.py", line 16, in <module>
class Controller(QtCore.QObject):
File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pyblish_qml\control.py", line 310, in Controller
def commentEnabled(self):
TypeError: A constant property cannot have a WRITE method or a NOTIFY signal.
```

**Comment by OlafHaag** [comment]
Ok, After changing the constant argument to False on https://github.com/pyblish/pyblish-qml/blob/507bb41a2935a63278a69716f99e74c4d8714ae1/pyblish_qml/control.py#L309, the pyblish_qml interface now actually loads!
The problem is still that I can't expect users to copy a DLL around. Would have to ask Blender devs if they are willing wo include it, but I also wouldn't want wo wait until that eventually happens. Any ideas?
And the other issue is one of pyblish_qml. So if there are no ideas for other workarounds, we're done here. Hope, this thread serves as a cautionary tale for others going down this path.

**Comment by hannesdelbeke** [comment]
hmm, how curious that it doesn't work for you @OlafHaag
When I ran it, it just worked. And I didn't do any qt installation for Blender.
I have however been working with Pyblish a lot recently so wonder if there are any configs on my pc that affect this.
Would be good to figure out what causes it.

**Comment by OlafHaag** [comment]
Just seeing your comment now, @hannesdelbeke . I did make it work last year, against all better judgement in Blender's Python distribution, without adding a new Python distro. Unfortunately, Blender abandoned their short endeavor in following VFX Platform guidelines, and now always use the latest Python version.
So far, it works for our inhouse use. I asked the Blender devs if at some point we'll be able to create native GUIs via add-ons, but it's not on their roadmap. A custom outliner view would have been great for pyblish.
